/* Dicionário compartilhado — nenhuma string solta no JSX. */

export const t = {
  pt: {
    nav: { products: "Produtos", eng: "Engenharia", how: "Como trabalho", about: "Empresa", contact: "Contato" },
    heroBadge: "Disponível para novos projetos e posições fullstack",
    h1a: "Antes de escrever código, ",
    h1b: "eu vou ver o seu problema de perto",
    lead: "Eu estudo o seu fluxo, acompanho o dia e escuto quem opera. Aprendo a sua língua antes de propor qualquer coisa, porque o problema quase nunca está onde alguém diz que está. Quando eu entendo na fonte, o sistema sai certo de primeira — e a sua equipe usa, em vez de contornar.",
    note: "Eu sou o Rafael. Passei quinze anos vendendo na rua antes de programar, então eu já fui quem depende do sistema para bater meta. É por isso que eu começo pela sua operação, não pela stack. A **Maldivas Tech** é a empresa por trás disso: CNPJ ativo, contrato e nota fiscal.",
    ctaWork: "Ver os produtos",
    ctaTalk: "Falar sobre um projeto",
    ctaGh: "GitHub",
    stats: [
      { n: "5", l: "plataformas completas construídas do zero" },
      { n: "500+", l: "commits só no ERP mercadinhosys" },
      { n: "pt · ja", l: "produto B2B bilíngue para o mercado japonês" },
      { n: "CNPJ", l: "ativo — contrato PJ e nota fiscal de serviço" },
    ],
    prodTag: "Meus Produtos",
    prodTitle: "Quatro sistemas meus, rodando agora",
    prodLead: "Cada um nasceu do mesmo jeito: eu fui ver a operação por dentro antes de desenhar qualquer tela. Não são apresentações. Todo link aqui embaixo abre o sistema de verdade, com gente usando do outro lado neste momento.",
    lblProblem: "A dor do mercado",
    lblSolution: "A Solução (SaaS)",
    lblRepo: "Ver repositório ↗",
    lblDemo: "Acessar a plataforma ↗",
    lblHire: "Contratar / assinar",
    lblPrivate: "Exclusivo B2B — sob contrato",
    engTag: "Engenharia",
    engTitle: "Três coisas de que eu não abro mão",
    engLead: "É aqui que quase todo sistema barato escorrega. O dono só percebe quando o estoque não bate no fim do mês e ninguém consegue explicar o porquê.",
    eng: [
      {
        h: "Invariante de negócio mora no banco",
        p: "Baixa de estoque, lançamento contábil e numeração de pedido são triggers dentro da transação. A aplicação pode cair, o deploy pode quebrar, dois processos podem concorrer — o saldo continua certo.",
      },
      {
        h: "Isolamento é Row Level Security",
        p: "Multi-tenancy por WHERE tenant_id depende de ninguém esquecer o WHERE. Uma query esquecida é vazamento entre clientes. A política no Postgres não esquece.",
      },
      {
        h: "Estoque é ledger, saldo é cache",
        p: "As movimentações são a fonte da verdade e são append-only. O saldo atual é derivado. Isso torna qualquer divergência auditável até a origem, em vez de inexplicável.",
      },
    ],
    capTag: "Capacidades",
    capTitle: "O que eu faço sem terceirizar para ninguém",
    caps: [
      { h: "UX, Produto e Condução em Scrum", i: ["Pesquisa com usuário real e mapeamento do fluxo atual", "Wireframe, protótipo navegável e design system em Figma", "Backlog priorizado, sprints e cerimônias com o Product Owner", "Teste de usabilidade e ajuste de funil até a conversão subir", "Um marco visível por semana em ambiente de homologação"] },
      { h: "Arquitetura Frontend Sênior", i: ["Interfaces de alta densidade com Tailwind CSS", "Three.js e Canvas (Konva) para renderização espacial", "Shaders GLSL e animação na GPU, não na main thread", "OCR client-side (Tesseract) e processamento pesado local", "Micro-interações, glassmorphism e acessibilidade nativa"] },
      { h: "Engenharia Backend & Alta Carga", i: ["Flask, Django, Node.js e Edge Functions", "PostgreSQL avançado — RLS, triggers e pgcrypto", "Filas assíncronas (Celery, Redis) para checkout sem atrito", "Integração homologada: iFood, WhatsApp Business API, Pix", "Auditoria imutável e desenho para zero downtime"] },
      { h: "Qualidade, Testes & DevOps", i: ["Teste de carga massiva com k6 e telemetria", "E2E com Playwright e Cypress travando PR que quebra", "Docker, CI/CD e entregas incrementais seguras", "PWA e estratégias offline-first resilientes", "Backup com restauração testada, não só agendada"] },
      { h: "Inteligência de Dados & Domínio Comercial", i: ["Modelagem preditiva e estatística (Pandas, Statsmodels)", "Dashboards interativos (Plotly, Recharts, Power BI)", "Curva ABC, matriz RFM e previsão de ruptura", "Pagamentos: Pix, cartão e split automático de receita", "LGPD by design e conformidade fiscal (NFC-e)"] },
      { h: "Conteúdo, Vídeo e Presença Digital", i: ["Vídeo institucional, motion e vinheta de marca", "Captação aérea com drone — piloto formado (ITARC)", "Corte, legenda e formato vertical para redes sociais", "Google Meu Negócio, Google Ads e Meta Ads", "Identidade visual e material impresso (Canva, Figma)"] },
    ],
    howTag: "Método",
    howTitle: "O diagnóstico vem antes de tudo",
    howLead: "Projeto de software dá errado quase sempre pelo mesmo motivo: alguém começou a construir antes de entender o problema. Eu inverto a ordem. Primeiro eu vejo a operação funcionando, depois a gente conversa sobre escopo.",
    steps: [
      { h: "Diagnóstico do processo", p: "Antes de falar de tecnologia, eu mapeio onde o dinheiro vaza, onde alguém redigita e onde o erro nasce. Esta etapa não é cobrada." },
      { h: "Escopo, prazo e preço", p: "Proposta escrita com o que entra, o que não entra, marcos de validação e condições de pagamento. Você aprova antes de começar." },
      { h: "Entrega com validação semanal", p: "Ambiente de homologação dedicado e um marco visível por semana. Você acompanha o sistema nascer, não recebe uma caixa fechada no fim." },
      { h: "Aceite e garantia", p: "Treinamento da equipe, termo de aceite e 90 dias de garantia técnica sobre tudo que estava no escopo." },
    ],
    aboutTag: "Empresa",
    aboutTitle: "Maldivas Tech",
    aboutBody: [
      "Sou **Rafael Maldivas**, engenheiro de software fullstack com foco em sistemas de gestão e análise de dados. Antes de programar, trabalhei com vendas — e é por isso que eu começo pelo processo, não pela stack. Software que ignora como a operação realmente funciona não é usado, por melhor que seja o código.",
      "A **Maldivas Tech** é a estrutura formal por trás desse trabalho: CNPJ ativo, contrato, nota fiscal de serviço e responsabilidade definida por escrito. Se você precisa de fornecedor que a área financeira consegue cadastrar, existe.",
      "Atendo **projeto B2B sob contrato** e também posições **fullstack em regime CLT ou PJ**, remoto no Brasil ou internacional. Nos dois casos eu entrego a mesma coisa: sistema que aguenta a operação real e código que a próxima pessoa consegue manter.",
    ],
    corp: "Dados da empresa",
    kv: [
      ["Razão social", "Rafael Paiva Dias da Silva Consultoria em Tecnologia da Informação LTDA"],
      ["Nome fantasia", "Maldivas Tech"],
      ["CNPJ", "68.923.239/0001-77"],
      ["Natureza jurídica", "Sociedade Empresária Limitada · porte ME"],
      ["CNAE principal", "62.01-5-01 — Desenvolvimento de programas de computador sob encomenda"],
      ["Situação cadastral", "Ativa desde 02/09/2026"],
      ["Sede", "R. Pais Leme, 215 · cj. 1713 — Pinheiros, São Paulo/SP · 05424-150"],
      ["Nota fiscal", "NFS-e de serviço, emitida mensalmente"],
      ["Responsável técnico", "Rafael Maldivas"],
    ],
    contactTitle: "Tem uma operação que precisa de sistema?",
    contactLead: "A conversa inicial e o diagnóstico do processo não têm custo. Se eu não for a melhor solução para o seu caso, eu digo isso na primeira reunião.",
    contactBtn: "Falar no WhatsApp",
    contactAlt: "Conversar no LinkedIn",
    contactEmail: "Enviar e-mail",
    contactFine: "Também disponível para posições fullstack — Brasil ou remoto internacional.",
    rights: "Todos os direitos reservados.",
  },
  en: {
    nav: { products: "Products", eng: "Engineering", how: "How I work", about: "Company", contact: "Contact" },
    heroBadge: "Available for new projects and fullstack roles",
    h1a: "Management systems for operations that ",
    h1b: "cannot go down",
    lead: "I build multi-tenant ERPs, fiscal POS, marketplaces and ATS platforms — from the data model to deployment. Software the operation uses every day, with tax invoicing, row-level access control and audit trails.",
    note: "Rafael Maldivas · Fullstack software engineer and data analyst. Founder of **Maldivas Tech** — registered Brazilian company issuing formal service invoices.",
    ctaWork: "See the products",
    ctaTalk: "Discuss a project",
    ctaGh: "GitHub",
    stats: [
      { n: "5", l: "complete platforms built from scratch" },
      { n: "500+", l: "commits on the mercadinhosys ERP alone" },
      { n: "pt · ja", l: "bilingual B2B product for the Japanese market" },
      { n: "B2B", l: "registered company — contracts and invoicing" },
    ],
    prodTag: "My Products",
    prodTitle: "Exclusive SaaS Platforms",
    prodLead: "Beyond working as a software engineer on custom B2B projects, I am the founder and maintainer of complete SaaS systems. Explore the platforms I build and operate in production.",
    lblProblem: "Market pain point",
    lblSolution: "The Solution (SaaS)",
    lblRepo: "View repository ↗",
    lblDemo: "Open the platform ↗",
    lblHire: "Get started",
    lblPrivate: "B2B exclusive — under contract",
    engTag: "Engineering",
    engTitle: "How I decide architecture",
    engLead: "Three decisions I'll defend in any technical conversation — and that show up in every system above.",
    eng: [
      {
        h: "Business invariants live in the database",
        p: "Inventory depletion, ledger entries and order numbering are triggers inside the transaction. The app can crash, a deploy can break, two processes can race — the balance stays correct.",
      },
      {
        h: "Isolation means Row Level Security",
        p: "Multi-tenancy via WHERE tenant_id depends on nobody forgetting the WHERE. One forgotten query is a cross-tenant leak. A Postgres policy doesn't forget.",
      },
      {
        h: "Inventory is a ledger; balance is a cache",
        p: "Movements are the source of truth and append-only. Current balance is derived. Any discrepancy becomes auditable back to its origin instead of unexplainable.",
      },
    ],
    capTag: "Capabilities",
    capTitle: "What I bring to the table",
    caps: [
      { h: "UX, Product and Scrum Delivery", i: ["Research with real users and mapping of today's flow", "Wireframes, clickable prototypes and a Figma design system", "Prioritised backlog, sprints and ceremonies with the Product Owner", "Usability testing and funnel tuning until conversion moves", "One visible milestone per week on a staging environment"] },
      { h: "Senior Frontend Architecture", i: ["High-density interfaces with Tailwind CSS", "Three.js and Canvas (Konva) for spatial rendering", "GLSL shaders and GPU animation, never the main thread", "Client-side OCR (Tesseract) and heavy local processing", "Micro-interactions, glassmorphism and native accessibility"] },
      { h: "Backend Engineering & High Load", i: ["Flask, Django, Node.js and Edge Functions", "Advanced PostgreSQL — RLS, triggers and pgcrypto", "Async queues (Celery, Redis) for frictionless checkout", "Approved integrations: iFood, WhatsApp Business API, Pix", "Immutable auditing and zero-downtime design"] },
      { h: "Quality, Testing & DevOps", i: ["Massive load testing with k6 and deep telemetry", "E2E with Playwright and Cypress blocking breaking PRs", "Docker, CI/CD and safe incremental shipping", "Resilient PWA and offline-first strategies", "Backups with restores actually tested, not just scheduled"] },
      { h: "Data Intelligence & Commercial Domain", i: ["Predictive modelling and statistics (Pandas, Statsmodels)", "Interactive dashboards (Plotly, Recharts, Power BI)", "ABC curves, RFM matrices and stockout forecasting", "Payments: Pix, card and automatic revenue split", "LGPD by design and fiscal compliance (NFC-e)"] },
      { h: "Content, Video & Digital Presence", i: ["Brand films, motion design and idents", "Aerial drone footage — certified pilot (ITARC)", "Cutting, captions and vertical formats for social", "Google Business Profile, Google Ads and Meta Ads", "Visual identity and print material (Canva, Figma)"] },
    ],
    howTag: "Method",
    howTitle: "How I work",
    howLead: "No scope surprises, no price surprises. Everything we agree on is written down before the first line of code.",
    steps: [
      { h: "Process diagnosis", p: "Before talking technology, I map where money leaks, where someone retypes data and where errors are born. This step is free." },
      { h: "Scope, timeline, price", p: "A written proposal with what's in, what's out, validation milestones and payment terms. You approve before anything starts." },
      { h: "Weekly validation", p: "A dedicated staging environment and one visible milestone per week. You watch the system take shape rather than receiving a sealed box at the end." },
      { h: "Acceptance and warranty", p: "Team training, a signed acceptance document and 90 days of technical warranty covering everything in scope." },
    ],
    aboutTag: "Company",
    aboutTitle: "Maldivas Tech",
    aboutBody: [
      "I'm **Rafael Maldivas**, a fullstack software engineer focused on management systems and data analysis. Before I wrote code, I worked in sales — which is why I start with the process, not the stack. Software that ignores how an operation actually runs doesn't get used, however good the code is.",
      "**Maldivas Tech** is the formal structure behind that work: a registered Brazilian company with contracts, service invoicing and written liability terms. If you need a vendor your finance team can actually onboard, it exists.",
      "I take on **contracted B2B projects** as well as **fullstack roles**, remote in Brazil or internationally. Either way you get the same thing: a system that survives real operational load, and code the next person can maintain.",
    ],
    corp: "Company details",
    kv: [
      ["Legal name", "Rafael Paiva Dias da Silva Consultoria em Tecnologia da Informação LTDA"],
      ["Trade name", "Maldivas Tech"],
      ["Tax ID (CNPJ)", "68.923.239/0001-77"],
      ["Legal form", "Brazilian limited company (LTDA) · small enterprise"],
      ["Primary activity", "62.01-5-01 — Custom software development"],
      ["Registry status", "Active since 2026-09-02"],
      ["Headquarters", "R. Pais Leme, 215 · suite 1713 — Pinheiros, São Paulo/SP · Brazil"],
      ["Invoicing", "Monthly service invoice (NFS-e)"],
      ["Technical lead", "Rafael Maldivas"],
    ],
    contactTitle: "Got an operation that needs a system?",
    contactLead: "The first conversation and the process diagnosis are free. If I'm not the best fit for your case, I'll tell you in the first meeting.",
    contactBtn: "Message on WhatsApp",
    contactAlt: "Connect on LinkedIn",
    contactEmail: "Send an email",
    contactFine: "Also available for fullstack roles — Brazil or international remote.",
    rights: "All rights reserved.",
  },
} as const;
